---
- name: Import common file
  import_playbook: ../static-assignments/common.yaml
  tags:
    - always

- name: Include dynamic variables
  import_playbook: ../dynamic-assignments/env-vars.yaml
  tags:
    - always

- hosts: uat-webservers
- import_playbook: ../static-assignments/uat-webservers.yaml

- name: Loadbalancers assignment
  import_playbook: ../static-assignments/loadbalancers.yaml
  when: load_balancer_is_required 